# Change these first
owner: JReyesPetroil
repo: upptime # The name of this repository

sites:
  - name: SIPP
    url: https://sipp.petroil.com.mx
  - name: Portal de Clientes
    url: https://asociados.petroil.com.mx
  - name: Gitlab
    url: https://git.grupopetroil.com.mx
  - name: HelpDesk
    url: https://soporte.petroil.dev
  - name: ProyectosTI
    url: https://proyectos.petroil.dev
  - name: OdooCRM
    url: https://crm.grupopetroil.com.mx/web/login
  - name: Pyxoom
    url: https://pyxoom.grupopetroil.com.mx/Helper/Home/Login
  - name: WPPetroil
    url: https://petroil.com.mx
  - name: WPGrupoPetroil
    url: https://grupopetroil.com.mx
  - name: WPAeneFoods
    url: https://aenefoods.com.mx
  - name: rentabilidad
    url: https://api.grupopetroil.com.mx/v1/rentabilidad
  - name: tableros
    url: https://api.grupopetroil.com.mx/v1/dashboards
assignees:
  - JReyesPetroil

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime**"
  introMessage: Petroil
  navbar:
    - title: Status
      href: /$REPO
    - title: GitHub
      href: https://$OWNER.github.io/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
