# Change these first
owner: JReyesPetroil
repo: upptime # The name of this repository

sites:
  - name: SIPP
    url: https://sipp.petroil.com.mx/login.html
  - name: Portal de Clientes
    url: https://asociados.petroil.com.mx
  - name: Gitlab
    url: https://git.grupopetroil.com.mx
  - name: HelpDesk
    url: https://soporte.petroil.dev
  - name: ProyectosTI
    url: https://proyectos.petroil.dev
  - name: OdooCRM
    url: https://crm.grupopetroil.com.mx/web/login
  - name: Pyxoom
    url: https://pyxoom.grupopetroil.com.mx/Helper/Home/Login
  - name: CPanel Paginas web
    url: https://petroil.com.mx/contacto/
  - name: Rentabilidad
    url: https://api.grupopetroil.com.mx/v1/rentabilidad
  - name: Tableros
    url: https://api.grupopetroil.com.mx/v1/dashboards
  - name: Personal
    url: https://api.grupopetroil.com.mx/v1/personal/health
  - name: Moodle Estudios Profesionales
    url: https://elearning.imexaa.mx/
assignees:
  - JReyesPetroil

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: estatus.petroil.dev
  # baseUrl: /upptime
  logoUrl: https://storage.googleapis.com/sipp-attachments/Empresas_Imagenes/imgReporte_Abastecedora_de_Combustibles.png
  name: upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
